<?php

return [
    'title'       => 'Hash Generator',
    'summary'     => 'Generate different types of hashes.',
    'description' => 'Password Generator allows you to generate hashes based on any data. The hashes generated by Hash Generator are calculated based on the algorithm you choose. These hashes are also secure as they are not sent over the internet and only exist on the client\'s machine.',

    'label' => 'Content to Hash',
    'placeholder' => 'Enter the content you want to hash.',
    'submit' => 'Generate'
];