<?php

return [
    'title'       => 'Password Generator',
    'summary'     => 'Generate secure random passwords.',
    'description' => 'Password Generator allows you to generate passwords based on many different settings. The passwords generated by Password Generator are randomized. These passwords are also secure as they are not sent over the internet and only exist on the client\'s machine.',

    'length' => 'Password Length',
    'symbols' => 'Include Symbols',
    'numbers' => 'Include Numbers',
    'lowercase' => 'Include Lowercase Characters',
    'uppercase' => 'Include Uppercase Characters',
    'ambiguous' => 'Include Ambiguous Characters',
    'submit' => 'Generate Password',
    'result-label' => 'Your New Password',
    'result-placeholder' => 'Your New Password will be here.'
];